python finetune.py \
    --base_model '/shared/data3/checkpoints/llama-2-13b-chat-hf' \
    --data_path './test_1k.json' \
    --output_dir './lora-llama2-13bchat-1k' \
    --batch_size 2 \
    --micro_batch_size 2 \
    --num_epochs 10 \
    --learning_rate 1e-4 \
    --cutoff_len 1024 \
    --val_set_size 25 \
    --lora_r 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --lora_target_modules '[q_proj,v_proj]' \
    --group_by_length